// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bruhBruh.Models;

#nullable disable

namespace bruhBruh.Migrations.Veggie
{
    [DbContext(typeof(VeggieContext))]
    [Migration("20241011121648_InitialVeggieMigration")]
    partial class InitialVeggieMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("bruhBruh.Models.veggies", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Value")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Weight")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Veggies");

                    b.HasData(
                        new
                        {
                            Name = "Celery",
                            Size = "Long",
                            Value = 2,
                            Weight = 1
                        },
                        new
                        {
                            Name = "Green Pepper",
                            Size = "Wide",
                            Value = 3,
                            Weight = 2
                        },
                        new
                        {
                            Name = "Habanero",
                            Size = "Small",
                            Value = 2,
                            Weight = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
